package gateway

import (
	"crypto/ed25519"
	"crypto/sha256"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"net/http"
	"net/http/httptest"
	"os"
	"strings"
	"testing"
	"time"

	"openmodel/sp-state-agent/internal/config"
	"openmodel/sp-state-agent/internal/worker"
)

// pyFixtureReceipt was generated by the REAL py-inference implementation
// (src/inference/receipt.py build_receipt) — verifying it here pins the canonical
// signing payload as byte-identical across the two languages. If either side's
// canonicalization drifts, this test fails.
const pyFixtureReceipt = `{"v":1,"request_id":"req-fixture01","model":"qwen3-8b","request_sha256":"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","response_sha256":"bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb","prompt_tokens":100,"completion_tokens":25,"cached_tokens":10,"ts":1783076903,"pubkey":"c97fc1342aaf0ffd760341a62937dcc9cbd72ed1fd0f10d793272559aacb765b","sig":"cf133c406300a59e3dee7b5d8eb67bf5baa40b522d197f963b7c586e035a0f968fc9e245fd058e61cd021bc3aad9e90ec9cef5913d63a01eb394ac16bfe4ee01"}`

func TestReceipt_CrossLanguageFixtureVerifies(t *testing.T) {
	var r ReceiptInfo
	if err := json.Unmarshal([]byte(pyFixtureReceipt), &r); err != nil {
		t.Fatal(err)
	}
	verifyReceipt(&r, r.Pubkey, nil, tokenUsage{}, false)
	if !r.Verified {
		t.Fatalf("python-signed fixture must verify in Go (canonical payload drift?): %s", r.VerifyError)
	}
	// Any field tamper breaks it.
	r2 := r
	r2.CompletionTokens = 26
	verifyReceipt(&r2, r2.Pubkey, nil, tokenUsage{}, false)
	if r2.Verified {
		t.Fatal("tampered token count must NOT verify")
	}
}

// signTestReceipt builds a worker-side receipt in Go for integration tests, using the
// same canonical payload the verifier rebuilds.
func signTestReceipt(priv ed25519.PrivateKey, pubHex, rid, model, reqSHA, respSHA string,
	pt, ct, cached int) string {
	r := &ReceiptInfo{V: 1, RequestID: rid, Model: model, RequestSHA256: reqSHA,
		ResponseSHA256: respSHA, PromptTokens: pt, CompletionTokens: ct,
		CachedTokens: cached, TS: time.Now().Unix(), Pubkey: pubHex}
	r.Sig = hex.EncodeToString(ed25519.Sign(priv, canonicalReceiptPayload(r)))
	b, _ := json.Marshal(r)
	return base64.StdEncoding.EncodeToString(b)
}

// Non-streaming: a worker-signed receipt arrives via the X-OM-Receipt header, is
// verified against the /health-advertised pubkey + the exact forwarded body + usage,
// and lands in the billing ledger row. A tampered signature is flagged, not dropped.
func TestReceipt_NonStreamingCapturedAndVerified(t *testing.T) {
	pub, priv, _ := ed25519.GenerateKey(nil)
	pubHex := hex.EncodeToString(pub)

	tamper := false
	up := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		body, _ := readAll(r)
		respText := "hello there"
		resp := fmt.Sprintf(`{"choices":[{"message":{"role":"assistant","content":%q}}],`+
			`"usage":{"prompt_tokens":6,"completion_tokens":2,"total_tokens":8}}`, respText)
		if r.Header.Get("X-Om-Receipt-Req") == "1" {
			reqSHA := fmt.Sprintf("%x", sha256.Sum256(body))
			respSHA := fmt.Sprintf("%x", sha256.Sum256([]byte(respText)))
			rcpt := signTestReceipt(priv, pubHex, r.Header.Get("X-Request-Id"), "default",
				reqSHA, respSHA, 6, 2, 0)
			if tamper {
				rcpt = signTestReceipt(priv, pubHex, r.Header.Get("X-Request-Id"), "default",
					reqSHA, respSHA, 6, 99, 0) // lies about tokens vs usage
			}
			w.Header().Set("X-OM-Receipt", rcpt)
		}
		w.Header().Set("Content-Type", "application/json")
		fmt.Fprint(w, resp)
	}))
	defer up.Close()

	logger := testLogger()
	registry := worker.NewRegistry(logger, "")
	registry.Register(worker.WorkerRegistration{ID: "w0", Endpoint: up.URL, SchedulerURL: up.URL, GPUCount: 1})
	registry.UpdateState("w0", "GPU_STATE_AVAILABLE", "running", 0, "default", 1)
	registry.SetFeatures("w0", []string{worker.FeatureReceipt}, pubHex)

	dir := t.TempDir()
	gw := New(registry, config.GatewayConfig{
		RequestTimeoutSec: 5,
		APIKeys:           []config.APIKey{{Key: "test", Name: "user1"}},
		RequestLogPath:    dir + "/requests.jsonl",
	}, logger)
	srv := httptest.NewServer(gw.Handler())
	defer srv.Close()
	defer gw.Close()

	if st := doChat(t, srv.URL, chatBody); st != 200 {
		t.Fatalf("want 200, got %d", st)
	}
	rec := lastLoggedRecord(t, dir+"/requests.jsonl")
	if rec.Receipt == nil {
		t.Fatal("ledger row must carry the worker receipt")
	}
	if !rec.Receipt.Verified {
		t.Fatalf("receipt must verify, got error: %s", rec.Receipt.VerifyError)
	}

	// Byzantine worker: receipt token counts contradict the response usage → flagged.
	tamper = true
	if st := doChat(t, srv.URL, chatBody); st != 200 {
		t.Fatalf("want 200, got %d", st)
	}
	rec = lastLoggedRecord(t, dir+"/requests.jsonl")
	if rec.Receipt == nil || rec.Receipt.Verified {
		t.Fatal("contradictory receipt must be flagged unverified (byzantine evidence)")
	}
}

// Streaming (filter mode): the om_receipt event is captured for the ledger and
// STRIPPED from the client stream.
func TestReceipt_StreamCapturedAndStripped(t *testing.T) {
	pub, priv, _ := ed25519.GenerateKey(nil)
	pubHex := hex.EncodeToString(pub)

	up := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		body, _ := readAll(r)
		w.Header().Set("Content-Type", "text/event-stream")
		w.WriteHeader(200)
		fmt.Fprint(w, "data: {\"choices\": [{\"delta\": {\"content\": \"Hi\"}}]}\n\n")
		fmt.Fprint(w, "data: {\"choices\": [], \"usage\": {\"prompt_tokens\": 3, \"completion_tokens\": 1, \"total_tokens\": 4}}\n\n")
		if r.Header.Get("X-Om-Receipt-Req") == "1" {
			reqSHA := fmt.Sprintf("%x", sha256.Sum256(body))
			respSHA := fmt.Sprintf("%x", sha256.Sum256([]byte("Hi")))
			rcptB64 := signTestReceipt(priv, pubHex, r.Header.Get("X-Request-Id"), "default", reqSHA, respSHA, 3, 1, 0)
			raw, _ := base64.StdEncoding.DecodeString(rcptB64)
			fmt.Fprintf(w, "data: {\"om_receipt\": %s}\n\n", raw)
		}
		fmt.Fprint(w, "data: [DONE]\n\n")
	}))
	defer up.Close()

	logger := testLogger()
	registry := worker.NewRegistry(logger, "")
	for _, id := range []string{"w0", "w1"} {
		registry.Register(worker.WorkerRegistration{ID: id, Endpoint: up.URL, SchedulerURL: up.URL, GPUCount: 1})
		registry.UpdateState(id, "GPU_STATE_AVAILABLE", "running", 0, "default", 1)
		registry.SetFeatures(id, []string{worker.FeatureContinuation, worker.FeatureReceipt}, pubHex)
	}
	dir := t.TempDir()
	gw := New(registry, config.GatewayConfig{
		RequestTimeoutSec: 5,
		APIKeys:           []config.APIKey{{Key: "test", Name: "user1"}},
		RequestLogPath:    dir + "/requests.jsonl",
		StreamResume:      true, // filter mode: receipts requested + stripped
	}, logger)
	srv := httptest.NewServer(gw.Handler())
	defer srv.Close()
	defer gw.Close()

	req, _ := http.NewRequest("POST", srv.URL+"/v1/chat/completions", strings.NewReader(resumeBody))
	req.Header.Set("Authorization", "Bearer test")
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		t.Fatal(err)
	}
	raw, _ := readAll2(resp)
	if strings.Contains(string(raw), "om_receipt") {
		t.Error("om_receipt event must be STRIPPED from the client stream")
	}
	rec := lastLoggedRecord(t, dir+"/requests.jsonl")
	if rec.Receipt == nil {
		t.Fatal("stream receipt must land in the ledger")
	}
	if !rec.Receipt.Verified {
		t.Fatalf("stream receipt must verify, got: %s", rec.Receipt.VerifyError)
	}
}

// F2 (soak v2): a streaming client that OPTS IN with X-OM-Receipt-Req gets the
// om_receipt event forwarded (capture-for-ledger unchanged) — parity with the
// non-streaming X-Om-Receipt header, so streaming spend is independently auditable.
// The opt-out case stays pinned by TestReceipt_StreamCapturedAndStripped above.
func TestReceipt_StreamForwardedWhenClientOptsIn(t *testing.T) {
	pub, priv, _ := ed25519.GenerateKey(nil)
	pubHex := hex.EncodeToString(pub)

	up := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		body, _ := readAll(r)
		w.Header().Set("Content-Type", "text/event-stream")
		w.WriteHeader(200)
		fmt.Fprint(w, "data: {\"choices\": [{\"delta\": {\"content\": \"Hi\"}}]}\n\n")
		fmt.Fprint(w, "data: {\"choices\": [], \"usage\": {\"prompt_tokens\": 3, \"completion_tokens\": 1, \"total_tokens\": 4}}\n\n")
		reqSHA := fmt.Sprintf("%x", sha256.Sum256(body))
		respSHA := fmt.Sprintf("%x", sha256.Sum256([]byte("Hi")))
		rcptB64 := signTestReceipt(priv, pubHex, r.Header.Get("X-Request-Id"), "default", reqSHA, respSHA, 3, 1, 0)
		raw, _ := base64.StdEncoding.DecodeString(rcptB64)
		fmt.Fprintf(w, "data: {\"om_receipt\": %s}\n\n", raw)
		fmt.Fprint(w, "data: [DONE]\n\n")
	}))
	defer up.Close()

	logger := testLogger()
	registry := worker.NewRegistry(logger, "")
	registry.Register(worker.WorkerRegistration{ID: "w0", Endpoint: up.URL, SchedulerURL: up.URL, GPUCount: 1})
	registry.UpdateState("w0", "GPU_STATE_AVAILABLE", "running", 0, "default", 1)
	registry.SetFeatures("w0", []string{worker.FeatureContinuation, worker.FeatureReceipt}, pubHex)
	dir := t.TempDir()
	gw := New(registry, config.GatewayConfig{
		RequestTimeoutSec: 5,
		APIKeys:           []config.APIKey{{Key: "test", Name: "user1"}},
		RequestLogPath:    dir + "/requests.jsonl",
		StreamResume:      true,
	}, logger)
	srv := httptest.NewServer(gw.Handler())
	defer srv.Close()
	defer gw.Close()

	req, _ := http.NewRequest("POST", srv.URL+"/v1/chat/completions", strings.NewReader(resumeBody))
	req.Header.Set("Authorization", "Bearer test")
	req.Header.Set("X-OM-Receipt-Req", "1") // client opts in
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		t.Fatal(err)
	}
	raw, _ := readAll2(resp)
	out := string(raw)
	if !strings.Contains(out, "om_receipt") {
		t.Error("opted-in client must receive the om_receipt event")
	}
	if !strings.Contains(out, "data: [DONE]") {
		t.Error("stream must still terminate with [DONE]")
	}
	// gateway-side capture + verification unchanged
	rec := lastLoggedRecord(t, dir+"/requests.jsonl")
	if rec.Receipt == nil || !rec.Receipt.Verified {
		t.Fatal("ledger capture+verify must be unaffected by forwarding")
	}
}

// F1 (soak v2): a syntactically invalid JSON body must be 400 (Bad Request), not the
// misleading 404 it used to fall into via extractModel→"unknown"→no-worker routing.
func TestBadJSONBodyIs400(t *testing.T) {
	logger := testLogger()
	registry := worker.NewRegistry(logger, "")
	registry.Register(worker.WorkerRegistration{ID: "w0", Endpoint: "http://127.0.0.1:1", SchedulerURL: "http://127.0.0.1:1", GPUCount: 1})
	registry.UpdateState("w0", "GPU_STATE_AVAILABLE", "running", 0, "default", 1)
	gw := New(registry, config.GatewayConfig{
		RequestTimeoutSec: 2,
		APIKeys:           []config.APIKey{{Key: "test", Name: "user1"}},
	}, logger)
	srv := httptest.NewServer(gw.Handler())
	defer srv.Close()
	defer gw.Close()

	req, _ := http.NewRequest("POST", srv.URL+"/v1/chat/completions", strings.NewReader("{not json"))
	req.Header.Set("Authorization", "Bearer test")
	req.Header.Set("Content-Type", "application/json")
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		t.Fatal(err)
	}
	resp.Body.Close()
	if resp.StatusCode != http.StatusBadRequest {
		t.Fatalf("malformed JSON body must be 400, got %d", resp.StatusCode)
	}
}

// --- small helpers ---

func readAll(r *http.Request) ([]byte, error) {
	defer r.Body.Close()
	buf := new(strings.Builder)
	b := make([]byte, 4096)
	for {
		n, err := r.Body.Read(b)
		buf.Write(b[:n])
		if err != nil {
			break
		}
	}
	return []byte(buf.String()), nil
}

func readAll2(resp *http.Response) ([]byte, error) {
	defer resp.Body.Close()
	buf := new(strings.Builder)
	b := make([]byte, 4096)
	for {
		n, err := resp.Body.Read(b)
		buf.Write(b[:n])
		if err != nil {
			break
		}
	}
	return []byte(buf.String()), nil
}

func lastLoggedRecord(t *testing.T, path string) RequestRecord {
	t.Helper()
	var rec RequestRecord
	// The log write races the handler return by a hair — poll briefly.
	for i := 0; i < 40; i++ {
		data, err := readFile(path)
		if err == nil {
			lines := strings.Split(strings.TrimSpace(string(data)), "\n")
			if len(lines) > 0 && lines[len(lines)-1] != "" {
				if json.Unmarshal([]byte(lines[len(lines)-1]), &rec) == nil && rec.RequestID != "" {
					return rec
				}
			}
		}
		time.Sleep(25 * time.Millisecond)
	}
	t.Fatal("no record appeared in request log")
	return rec
}

func readFile(path string) ([]byte, error) {
	f, err := osOpenFile(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()
	buf := new(strings.Builder)
	b := make([]byte, 8192)
	for {
		n, err := f.Read(b)
		buf.Write(b[:n])
		if err != nil {
			break
		}
	}
	return []byte(buf.String()), nil
}

func osOpenFile(path string) (*os.File, error) { return os.Open(path) }
